require "options"
require "utils"
require "pluginList"
require "keymaps"
require "theme"

--
require "plugins.cmp"
require "plugins.lsp"
require "plugins.telescope"
require "plugins.treesitter"
require "plugins.autopairs"
require "plugins.comment"
require "plugins.lualine"
require "plugins.indent-blankline"
require "plugins.nnn"
